name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version for the release'
        required: true
        default: 'vX.Y.Z'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install python-setuptools  cmake build-essential ninja-build python-dev libffi-dev libssl-dev gcc-arm-none-eabi
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py # Fetch get-pip.py for python 2.7 
          python get-pip.py
          pip install yotta

      - name: Checkout 'develop' branch
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Update placeholder in `module.json` with release version ${{ github.event.inputs.release_version }}-bluetooth-disabled
        run: |
          sed -i -e"s@<to-be-replaced>@${{ github.event.inputs.release_version }}-bluetooth-disabled@g" module.json

      - name: Build static libraries for non-Bluetooth devices
        run: |
          yotta target calliope-mini-classic-gcc@https://github.com/calliope-mini/target-calliope-mini-classic-gcc
          yotta build

      - name: Prepare release for non-Bluetooth devices
        run: |
          mkdir -p /tmp/release-prep
          cd build/calliope-mini-classic-gcc/
          cp source/microbit.a /tmp/release-prep/
          cp ym/ble/source/ble.a ym/ble-nrf51822/source/ble-nrf51822.a ym/mbed-classic/existing/mbed-classic.a ym/microbit-dal/source/microbit-dal.a ym/nrf51-sdk/source/nrf51-sdk.a /tmp/release-prep
          cd ../../yotta_targets/calliope-mini-classic-gcc/
          cp bootloader/* ld/* softdevice/* /tmp/release-prep

      - name: Update placeholder in `module.json` with release version ${{ github.event.inputs.release_version }}-bluetooth-enabled
        run: |
          sed -i -e"s@-bluetooth-disabled@-bluetooth-enabled@g" module.json

      - name: Build static libraries for Bluetooth devices
        run: |
          yotta clean
          rm -rf yotta_modules/microbit-dal
          yotta build

      - name: Prepare release for Bluetooth devices
        run: |
          cd build/calliope-mini-classic-gcc/
          cp source/microbit.a /tmp/release-prep/microbit-b.a
          cp ym/mbed-classic/existing/mbed-classic.a  /tmp/release-prep/mbed-classic-b.a
          cp ym/microbit-dal/source/microbit-dal.a  /tmp/release-prep/microbit-dal-b.a
          cd ../../yotta_modules/
          cp -r * /tmp/release-prep/

      - name: Pack release
        id: pack_release
        run: |
          cd /tmp/release-prep
          zip -r microbit.zip .

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          release_name: ${{ github.event.inputs.release_version }}
          draft: false
          prerelease: true

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/release-prep/microbit.zip
          asset_name: microbit.zip
          asset_content_type: application/zip
